# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da61586f55c68e843d7f3ed8ffe637b08eb07bf45ef876a5fbe194de7f81ba6e10110beb3f9e49b6fa6acef40df2a1134b80bf270ad5e6bfb6090a3447972a89

test:
  secret_key_base: 50843550ae7e16d82feab6341f322e4f68eec75a31d0ea0a956fdc71f8ed109acb2ac6fe3678df0a46b8b09b5dfadbfad934946e0d417c305c581fb24515f370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
